stages:
  - deploy

s3_deploy:
  image: sleavely/node-awscli:14.x
  stage: deploy
  script:
    - npm install
    - npm run build
    - echo "Pushing the static files"
    - aws s3 sync build/ s3://christieziegler.com/ --acl public-read
    - echo "Clearing cloudfront cache"
    - aws cloudfront create-invalidation --distribution-id E3MSMFVLDFBKM1 --paths "/*" 
  only:
    - main

